"""create tags and asset_tags tables

Revision ID: f369fc41b5c7
Revises: ac3fcba280c1
Create Date: 2026-09-25 22:33:45.899752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f369fc41b5c7'
down_revision = 'ac3fcba280c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50, collation='NOCASE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tags_name')
    )
    op.create_table('asset_tags',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='fk_asset_tags_asset_id_assets', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_asset_tags_tag_id_tags', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id')
    )
    with op.batch_alter_table('asset_tags', schema=None) as batch_op:
        batch_op.create_index('idx_asset_tags_tag', ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_asset_tags_tag')

    op.drop_table('asset_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
